name: Build APK with Expo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: echo "Authenticated with Expo"

      - name: Debug Authentication
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: echo "Using EXPO_TOKEN: $EXPO_TOKEN"


      - name: Build APK
        run: eas build --platform android --non-interactive
